#!/usr/bin/env lua

require "lfs"
local cjson = require "cjson"
local commands = require "mnhbt.commands"
local consts = require "mnhbt.consts"
local data = require "mnhbt.data"

function getAndUpdateStreak(habit)
	if habit[consts.YESTERDAY] then
		return habit.meta.streak
	elseif habit[consts.TODAY] then
		habit.meta.streak = 1
		return 1
	end
	habit.meta.streak = 0
	return 0
end

function updateStreaks(habits)
	for k, _ in pairs(habits) do
		getAndUpdateStreak(habits[k])
	end
end

local success, habits = pcall(data.loadHabits)
if not success then
	io.write("Could not load habits file, would you like to create one? (y/n) ")
	io.flush()
	if io.read() ~= "y" then return end
end

local argRemainder = {}
for i = 2, #arg do
	argRemainder[i-1] = arg[i]
end

assert(commands.tryRun(arg[1], argRemainder, habits))
data.saveHabits()

